config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :expenses
    end
  end

  resources :expenses
  get '/dashboard', to: "dashboard#index"
  root "dashboard#index"
end

app/controllers/api/v1/expenses_controller.rb
module Api
  module V1
    class ExpensesController < ApplicationController
      protect_from_forgery with: :null_session
      respond_to :json

      def index
        @expenses = Expense.all

        if params[:type_id].present?
          @expenses = @expenses.find_type_id(params[:type_id].to_i)
        end
        
        if params[:category_id].present?
          @expenses = @expenses.find_category_id(params[:category_id].to_i)
        end

        if params[:type].present?
          @expenses = @expenses.find_type(params[:type].to_s.capitalize)
        end
        
        if params[:category].present?
          @expenses = @expenses.find_category(params[:category].to_s.capitalize)
        end

        if params[:year].present?
          @expenses = @expenses.find_year(params[:year].to_i)
        end

        if params[:month].present?
          @expenses = @expenses.find_month(params[:month].to_i)
        end

        if params[:day].present?
          @expenses = @expenses.find_day(params[:day].to_i)
        end

        if params[:beginDate].present?
          @expenses = @expenses.find_by_begindate(params[:beginDate].to_date)
        end

        if params[:endDate].present?
          @expenses = @expenses.find_by_enddate(params[:endDate].to_date)
        end

        if params[:concept].present?
          @expenses = @expenses.find_by_concept(params[:concept].to_s)
        end

        if params[:page].present?
          @expenses = @expenses.paginate(:page => params[:page], :per_page => 10)
        end

        if params[:startAmount].present?
          @expenses = @expenses.find_by_startAmount(params[:startAmount].to_i)
        end

        if params[:endAmount].present?
          @expenses = @expenses.find_by_endAmount(params[:endAmount].to_i)
        end

        render json: @expenses
      end

      def create
        expense = Expense.new(safe_params)
        if expense.save
          render json: expense, status: 201
        else
          render json: { errors: expense.errors }, status: 422
        end
      end

      def update
        expense = Expense.find(params[:id])
        if expense.update(safe_params)
          render json: expense, status: 200
        else
          render json: {errors: expense.errors}, status: 422
        end
      end

      def destroy
        expense = Expense.find(params[:id])
        expense.destroy
        head :no_content
      end

      private
      def safe_params
        params.require(:expense).permit(:type_id, :date, :category_id, :concept, :amount)
      end
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  respond_to :html, :js

  def index
    @tab = :expenses
    @categories = Category.all
    @types = Type.all
    @months = generate_last_n_months (12)

    @current_month = @months[params[:date].to_i]

    month = @current_month.month
    year = @current_month.year

    @expenses = Expense.find_year(year).find_month(month).order(date: :desc)

    if params[:type_id].present?
      @expenses = @expenses.find_type_id(params[:type_id].to_i)
    end
    
    if params[:category_id].present?
      @expenses = @expenses.find_category_id(params[:category_id].to_i)
    end

    respond_to do |format|
      format.js
      format.html {render 'index'}
    end

  end

  def new
    @expense = Expense.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    puts params[:date]
    @categories = Category.all
    @types = Type.all
    @expense = Expense.new safe_params
    @alert_msg = ''
    if @expense.save
      @alert_msg = 'Expense successfully created'
    else
      render :new
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def edit
    @expense = Expense.find params[:id]
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    @categories = Category.all
    @types = Type.all
    @alert_msg = ''
    @expense = Expense.find params[:id]
    @old_amount = @expense.amount
    if @expense.update safe_params
      @alert_msg = 'Expense successfully updated'
    else
      render :edit
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def destroy
    @alert_msg = ''
    @expense = Expense.find params[:id]
    @expense.destroy
    @alert_msg = 'Expense successfully deleted'
  end

  protected

  def safe_params
    params.require(:expense).permit(:type_id, :date, :category_id, :concept, :amount)
  end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_alert.html.erb
<div class="alert alert-success alert-dismissible" style="position: absolute;top: 8.2%;right: 10%;z-index: 1;" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%=@alert_msg%>
</div>

app/views/expenses/_edit_form.html.erb
<div class="edit-form-modal">
  <%=form_for @expense, html: {class: 'new-expense-form'}, remote: true do |f| %>
  <h2>Expense</h2>
  <% if !@expense.errors.messages.empty?%>
  <% @expense.errors.full_messages.each do |error| %>
    <p1><%= error%> </p1> <br>
  <%end%>
<% end %>
  <hr>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :type_id%>  <br>
      <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :date%> <br>
      <%=f.date_field :date, class: 'form-control'%>
    </div>
  </div> <br>
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <%=f.label :concept%> <br>
      <%=f.text_field :concept, class: 'form-control'%>
    </div>
  </div> <br>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :category_id%> <br>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :amount%> <br>
      <%=f.number_field :amount, class: 'form-control'%>
    </div>
  </div> <br>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-6 col-lg-5 col-lg-offset-7">
      <button type=button class="btn btn-default cancel-new-expense">Cancel</button>
    <%=f.submit 'Edit expense', class: "btn btn-primary create-expense"%>
    </div>
  </div>
  <% end %>
</div>

app/views/expenses/_form.html.erb
<table id="expenses-table" class="table table-hover" style="margin-top: 20px;">
  <thead>
    <tr>
      <th class="text-center">Day</th>
      <th>Concept</th>
      <th class="text-right">Category</th>
      <th class="text-right">Value</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
    <tr data-id='<%= expense.id%>'>
      <td class="date">
        <div class="day"><%= expense.date.strftime('%d')%></div>
        <div class="month"><%= expense.date.strftime('%b')%></div>
      </td>
      <td>
        <div>
          <span class="type"><%= @types.find {|i| i.id == expense.type_id}.name%></span>
        </div>
        <div>
          <span class="concept"><%= expense.concept%></span>
        </div>
      </td>
      <td class="category text-right"><%= @categories.find {|i| i.id == expense.category_id}.name%></td>
      <td class="text-right" style="width: 170px;">
        <div class="amount"><%=number_to_currency(expense.amount, :unit => "$") %></div>
        <div class="actions">
          <%=link_to "<span class='glyphicon glyphicon-edit'></span> edit".html_safe, edit_expense_path(expense.id), :class => "edit", remote: true%>
          <%=link_to "<span class='glyphicon glyphicon-trash'></span> delete".html_safe, expense_path(expense.id), :class => "delete",:data => {:confirm => "You sure?",:method => "delete", remote: true} %>
          </div>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/expenses/_new_expense.html.erb
<tr data-id='<%= @expense.id%>'>
  <td class="date">
    <div class="day"><%= @expense.date.strftime("%d")%></div>
    <div class="month"><%= @expense.date.strftime("%b")%></div>
  </td>
  <td>
    <div>
      <span class="type"><%= @types.find {|i| i.id == @expense.type_id}.name%></span>
    </div>
    <div>
      <span class="concept"><%= @expense.concept%></span>
    </div>
  </td>
  <td class="category text-right"><%= @categories.find {|i| i.id == @expense.category_id}.name%></td>
  <td class="text-right" style="width: 170px;">
    <div class="amount"><%= @expense.amount %></div>
    <div class="actions">
      <%=link_to "<span class='glyphicon glyphicon-edit'></span> edit".html_safe, edit_expense_path(@expense.id), remote: true%>
      <%=link_to "<span class='glyphicon glyphicon-trash'><span> delete".html_safe, expense_path(@expense.id),:data => {:confirm =>"You sure?",:method => 'delete', remote: true} %>
      </div>
      </td>
    </tr>

app/views/expenses/_new_form.html.erb
<div class="new-form-modal">
  <%=form_for @expense, html: {class: 'new-expense-form'}, remote: true do |f| %>
  <h2>Expense</h2>
  <% if !@expense.errors.messages.empty?%>
  <% @expense.errors.full_messages.each do |error| %>
    <p1><%= error%> </p1> <br>
  <%end%>
<% end %>
  <hr>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :type_id%>  <br>
      <%= f.collection_select(:type_id, Type.all, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :date%> <br>
      <%=f.date_field :date, class: 'form-control'%>
    </div>
  </div> <br>
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <%=f.label :concept%> <br>
      <%=f.text_field :concept, class: 'form-control'%>
    </div>
  </div> <br>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :category_id%> <br>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {:class => 'form-control'}) %>
    </div>
    <div class="col-xs-12 col-md-6 col-lg-6">
      <%=f.label :amount%> <br>
      <%=f.number_field :amount, class: 'form-control'%>
    </div>
  </div> <br>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-6 col-lg-5 col-lg-offset-7">
      <button type=button class="btn btn-default cancel-new-expense">Cancel</button>
    <%=f.submit 'Create expense', class: "btn btn-primary create-expense"%>
    </div>
  </div>
  <% end %>
</div>

app/views/expenses/_summary.html.erb
<div class="summary-box col-md-4 text-center">
  <div class="summary-value total">
    <%total = 0%>
    <%@expenses.each do |i| %>
    <%total += i.amount%>
    <%end%>
    <%=number_to_currency(total, :unit => "$")%>
  </div>
  <div class="summary-label">Total</div>
</diV>
<div class="summary-box col-md-4 text-center">
  <div class="summary-value quantity"><%= tansactions = @expenses.count %></div>
  <div class="summary-label">Transactions</div>
</div>
<div class="summary-box col-md-4 text-center">
  <div class="summary-value average"><%=tansactions == 0 ? 0 : number_to_currency(total/tansactions, :unit => "$") %></div>
  <div class="summary-label">Average</div>
</div>

app/views/expenses/create.js.erb
$('.new-form-modal').fadeOut(300)

const viewer_month = $('.dropdown-toggle').text()
const expense_month = '<%=@expense.date.strftime("%B %Y")%>'

if (viewer_month === expense_month) {

  const visited_type = $('.filter-type .visited').text()
  const visited_category = $('.filter-category .visited').text()

  if ((visited_type == "" && visited_category == "") ||
  (visited_type == '<%=@expense.type.name%>' && visited_category == "") ||
  (visited_category == '<%=@expense.category.name%> '&& visited_type == "") ||
  (visited_category == '<%=@expense.category.name%>' && visited_type == '<%=@expense.type.name%>'))
  {

    $('tbody').prepend(`<%=j render('new_expense')%>`)
    const total = parseInt($('.total').text()) + <%=@expense.amount%>
    const quantity = parseInt($('.quantity').text()) + 1
    const average = total/quantity
    $('.total').text(`${total}`)
    $('.quantity').text(`${quantity}`)
    $('.average').html(average.toFixed(2))

  }
}

$('.alert-container').prepend('<%=j render ("alert")%>')
$('.alert-container').fadeIn(600)

app/views/expenses/destroy.js.erb
$('tbody').find('[data-id=<%=@expense.id%>]').fadeOut(300)

const total = parseInt($('.total').text()) - <%=@expense.amount%>
const quantity = parseInt($('.quantity').text()) - 1
const average = total/quantity
$('.total').text(`${total}`)
$('.quantity').text(`${quantity}`)
$('.average').html(average.toFixed(2))

$('.alert-container').prepend('<%=j render ("alert")%>')
$('.alert-container').fadeIn(600)

app/views/expenses/edit.js.erb
$('.new-indicator').html('<%= j render("edit_form")%>')
$('.cancel-new-expense').on('click', () => {
  $('.new-expense-form').fadeOut(300)
})

app/views/expenses/index.html.erb
<% flash.each do |name, msg| -%>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= msg %>
</div>
<% end %>
<div class="container">
  <div class="alert-container" style="display: none"></div>
  <div class="row">
    <div class="col-md-3">
      <h4 class="filter-header">Transaction Type <span>Choose to filter</span></h4>

      <div class="list-group filter-type">
        <% @types.each do |type|%>
        <%= link_to type.name, expenses_path, class: 'list-group-item', tid: type.id%>
        <% end %>
      </div>

      <h4 class="filter-header">Transaction Category <span>Choose to filter</span></h4>

      <div class="list-group filter-category">
        <% @categories.each do |category|%>
        <%= link_to category.name, expenses_path, class: 'list-group-item', cid: category.id%>
        <% end %>
      </div>
    </div>
    <div class='new-indicator'></div>
    <div class="col-md-9">
      <div class="row summary-container" style="margin-top: 10px;">
        <div class="summary-box col-md-4 text-center">
          <div class="summary-value total">
            <%total = 0%>
            <%@expenses.each do |i| %>
            <%total += i.amount%>
            <%end%>
            <%=number_to_currency(total, :unit => "$")%>
          </div>
          <div class="summary-label">Total</div>
        </diV>
        <div class="summary-box col-md-4 text-center">
          <div class="summary-value quantity"><%= tansactions = @expenses.count %></div>
          <div class="summary-label">Transactions</div>
        </div>
        <div class="summary-box col-md-4 text-center">
          <div class="summary-value average"><%=tansactions == 0 ? 0 : number_to_currency(total/tansactions, :unit => "$") %></div>
          <div class="summary-label">Average</div>
        </div>
      </div>

      <div class="row" style="margin-top: 20px;">
        <div class="col-md-12">
          <%= link_to "<span class='glyphicon glyphicon-plus'></span> New Expense".html_safe, new_expense_path, class: 'btn btn-success pull-left', remote: true %>
          <!-- <a href="#" class="btn btn-success pull-left"> New Expense</a> -->
          <h4 class="dropdown pull-right">
            <button type="button" class="dropdown-toggle btn btn-link" data-toggle="dropdown"><%= @current_month.strftime("%B %Y") %><span class="caret"></span></button>
            <ul class="dropdown-menu" role="menu">
              <% @months.each_with_index do |month, index| %>
              <li role="presentation"><%= link_to month.strftime("%B %Y"), expenses_path, month_index: index, class: 'month-item'  %></li>
              <% end %>
            </ul>
          </h4>
        </div>
      </div>
      <div class="index-data">
        <%=render("form")%>
      </div>
    </div>
  </div>
</div>
</div>

app/views/expenses/index.js.erb
$('.index-data').html('<%= j render("form")%>')
$('.summary-container').html('<%= j render("summary")%>')

app/views/expenses/new.js.erb
$('.new-indicator').html('<%= j render("new_form")%>')
$('.cancel-new-expense').on('click', () => {
  $('.new-expense-form').fadeOut(300)
})

app/views/expenses/update.js.erb
$(".edit-form-modal").fadeOut(300)
$('tbody').find('[data-id=<%=@expense.id%>]').fadeOut(300)

const viewer_date = $('.dropdown-toggle').text()
const expense_date = '<%=@expense.date.strftime("%B %Y")%>'

if (viewer_date === expense_date) {

  const total = parseInt($('.total').text()) - <%=@old_amount%> + <%=@expense.amount%>
  const quantity = parseInt($('.quantity').text())
  const average = total/quantity

  $('tbody').prepend(`<%=j render('new_expense')%>`)
  $('.total').text(`${total}`)
  $('.quantity').text(`${quantity}`)
  $('.average').html(average.toFixed(2))

} else {
  const total = parseInt($('.total').text()) - <%=@old_amount%>
  const quantity = parseInt($('.quantity').text()) - 1
  const average = total/quantity

  $('.total').text(`${total}`)
  $('.quantity').text(`${quantity}`)
  $('.average').html(average.toFixed(2))
}

$('.alert-container').prepend('<%=j render ("alert")%>')
$('.alert-container').fadeIn(600)